#############################################################
#1. Model Define Configs
#############################################################
ModelConfig:
  model_name: 'ResECG'
  num_filters_1st_conv: 32
  kernel_size_conv: 15
  Strides_ResBlock: [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]
  conv_increase_channels_at: 4
  conv_num_skip: 2
  dropout_rate: 0.2 
  num_classes: 4

#############################################################
#2. Optimizer & Train Configs
# loss: CrossEntropyLoss or FocalLoss 
# base unbalance weight: [0.03572452,0.07508805,0.23923172,0.64995571]
#############################################################
OptimizerConfig:
  epoches: 100
  learning_rate: 0.001
  loss: 'CrossEntropyLoss'
  use_unbalance_weight: True
  class_weight: [0.03572452,0.07508805,0.23923172,0.64995571]

#############################################################
#    3. DataSet Config
#############################################################  
DatasetConfig:
  filelist_root: './experiments/cinc17/'
  trainlist: 'train.json'
  validlist: 'valid.json'
  batch_size: 64
  num_workers: 8
  shuffle: True
  step: 256

